[package]
name = "core_logic"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]
name = "core_logic"

[dependencies]
uniffi = { version = "0.29" }

[build-dependencies]
uniffi = { version = "0.29", features = ["build"] }
